import { invoke } from "@tauri-apps/api/core";
import type {
  ApiConnection, BatchRequest, CaptionEditBatch, CaptionEditRule, CaptionVersion,
  ConnectionTestResult, EditBatchRecord, HistoricalStats, ImageJob, LocalModelState,
  LoraMetadataReport, LoraSanitizeResult, ModelOption, RevisionPreset, StatsBreakdown, StatsQuery, TagPreset, TaskRuntimeState,
  UndoBatchResult,
} from "../types";

export const backend = {
  bootstrap: () => invoke<{ connections: ApiConnection[]; tagPresets: TagPreset[]; revisionPresets: RevisionPreset[] }>("bootstrap"),
  saveConnection: (connection: ApiConnection) => invoke<ApiConnection>("save_connection", { connection }),
  deleteConnection: (id: string) => invoke<void>("delete_connection", { id }),
  testConnection: (connectionId: string) => invoke<ConnectionTestResult>("test_connection", { connectionId }),
  listModels: (connectionId: string, force = false) => invoke<ModelOption[]>("list_models", { connectionId, force }),
  selectImages: (multiple: boolean) => invoke<ImageJob[]>("select_images", { multiple }),
  selectFolder: (recursive: boolean) => invoke<ImageJob[]>("select_folder", { recursive }),
  selectTextFiles: () => invoke<string[]>("select_text_files"),
  selectTextFolder: (recursive: boolean) => invoke<string[]>("select_text_folder", { recursive }),
  selectLoraFiles: () => invoke<LoraMetadataReport[]>("select_lora_files"),
  inspectLoraMetadata: (paths: string[]) => invoke<LoraMetadataReport[]>("inspect_lora_metadata", { paths }),
  sanitizeLoraMetadata: (paths: string[]) => invoke<LoraSanitizeResult[]>("sanitize_lora_metadata", { paths }),
  loadThumbnails: (paths: string[]) => invoke<Record<string, string>>("load_thumbnails", { paths }),
  selectFolderPath: (recursive: boolean) => invoke<string | null>("select_folder_path", { recursive }),
  scanFolderPaths: (folder: string, recursive: boolean) => invoke<string[]>("scan_folder_paths", { folder, recursive }),
  scanFolderJobs: (folder: string, recursive: boolean) => invoke<ImageJob[]>("scan_folder_jobs", { folder, recursive }),
  sampleImages: (folder: string, count: number, recursive: boolean) => invoke<ImageJob[]>("sample_images", { folder, count, recursive }),
  applySample: (folder: string, keptPaths: string[]) => invoke<[string[], string[]]>("apply_sample", { folder, keptPaths }),
  moveAiSampleImage: (folder: string, path: string, keep: boolean) => invoke<[string, string]>("move_ai_sample_image", { folder, path, keep }),
  returnAiSampleImage: (folder: string, path: string) => invoke<[string, string]>("return_ai_sample_image", { folder, path }),
  resetAiSample: (folder: string) => invoke<[string[], string[]]>("reset_ai_sample", { folder }),
  getImagePreview: (path: string, maxDimension: number) => invoke<string | null>("get_image_preview", { path, maxDimension }),
  savePreset: (kind: "tag" | "revision", preset: TagPreset | RevisionPreset) => invoke<void>("save_preset", { kind, preset }),
  deletePreset: (kind: "tag" | "revision", id: string) => invoke<void>("delete_preset", { kind, id }),
  startBatch: (request: BatchRequest) => invoke<string>("start_batch", { request }),
  cancelBatch: (batchId: string) => invoke<void>("cancel_batch", { batchId }),
  getTaskRuntime: (batchId: string) => invoke<TaskRuntimeState | null>("get_task_runtime", { batchId }),
  listLocalModels: () => invoke<LocalModelState[]>("list_local_models"),
  ignoreReviewError: (captionPath: string) => invoke<void>("ignore_review_error", { captionPath }),
  downloadLocalModel: (modelId: string) => invoke<void>("download_local_model", { modelId }),
  saveCaption: (path: string, content: string, source: string) => invoke<void>("save_caption", { path, content, source }),
  previewEdit: (paths: string[], rule: CaptionEditRule) => invoke<CaptionEditBatch>("preview_caption_edit", { paths, rule }),
  applyEdit: (previewBatchId: string) => invoke<CaptionEditBatch>("apply_caption_edit", { previewBatchId }),
  listVersions: (path?: string) => invoke<CaptionVersion[]>("list_versions", { path }),
  listEditBatches: () => invoke<EditBatchRecord[]>("list_edit_batches"),
  queryStats: () => invoke<HistoricalStats>("query_stats"),
  queryStatsBreakdown: (query: StatsQuery) => invoke<StatsBreakdown>("query_stats_breakdown", { query }),
  restoreVersion: (versionId: number) => invoke<void>("restore_version", { versionId }),
  undoBatch: (batchId: string) => invoke<UndoBatchResult>("undo_edit_batch", { batchId }),
};
